### PR TITLE
make "debug" object available in error views including email address

### LINKED ISSUE #26: make more debugging details available in the error view
one of our projects is showing _quite_ a lot of detail to the "_end-user_" in the error template.
we need to make this info available, including the currently logged-in-person's email address if it's on the `request.auth.credentials` object.

### PR DESCRIPTION
**Pull request by nelsonic**
@iteles / @naazy this is ready for review. most of the additions are tests and docs. 
(_as you can tell from the CodeCov report, only one line added to the actual module..._ :wink:)
for / fixes https://github.com/dwyl/hapi-error/issues/26

### CODE REVIEW

**Comment by iteles** [comment]
Thanks @nelsonic ! Please assign back to us when you'd like a review/merge 😊

**Comment by nelsonic** [comment]
@iteles i would rather _not_ be doing this actually... 
this is the _perfect_ task for someone else to take off my hands... 😢

**Comment by iteles** [comment]
No reason why @naazy can't take this off your hands @nelsonic as we need it to roll into OA!

**Comment by nelsonic** [comment]
@naazy if you don't mind _reviewing_ (_and if everything is 'aight, merging_) this PR ... (_thanks!_)

**Comment by naazy** [comment]
Thanks @nelsonic ! Sorry I didn't take this off your hands 👐  sooner! I just reviewed and tried out this branch with https://github.com/OxfordAbstracts/application/pull/1543 and it worked perfectly! Thanks so much for your work on this - added bonus that we don't need to require hoek every time 😄

**Comment by nelsonic** [comment]
Yeah, requiring `hoek` in all the handlers was getting "old" ... 😉 
(_thanks for reviewing/merging_)

**Pull request merged**
