### PR TITLE
Added BSD 3 Clause License

### PR DESCRIPTION
**Pull request by tejzpr**

### CODE REVIEW

**Comment by tejzpr** [comment]
PR for #82

**Comment by nelsonic** [comment]
Hi @tejzpr thanks for opening this PR. 👍 
Please also update the https://github.com/dwyl/hapi-error/blob/master/package.json#L21 🙏

**Comment by tejzpr** [comment]
@nelsonic  I've updated the License in package.json as well.

**Review by nelsonic — APPROVED** [review]
@tejzpr thanks for updating the license. 
Even though we _prefer_ **`GPL`**, see: https://github.com/dwyl/intellectual-property#frequently-asked-questions-faq
We _totally_ understand that some organisations simply _cannot_ [for whatever reason] use code that is under that license. 
Since _we_ are no longer using `Hapi` for our projects; but know that plenty of people still are. We are happy for the community to decide what license is most appropriate. 
Thank you for this PR. 👍 

I've given you write-access to the repo so if you want to help maintain it, you're very welcome. 👌

**Pull request merged**
