### PR TITLE
Update tests issue #71

### LINKED ISSUE #71: Incomplete Tests
I did just a `git pull` on `master` in order to _attempt_ to publish a new version of the package
and when I try to run `npm version` I see the following error message:
```
npm ERR! ERROR: Coverage for branches (94.12%) does not meet global threshold (100%)
```
image

We need to write at _least_ one new test for the new functionality added by #70 for #69 
to ensure that any _future_ refactoring/updates do not create regressions.

Running `npm test` we see that the "uncovered" lines are _branches_ on `118` and `121`:
image

Viewing the coverage report in the browser confirms my suspicion:
hapi-error/coverage/lcov-report/index.js.html
image
The uncovered lines relate to the `redirect` if statements (_branches_) not having an `else` ...

Also, it appears that Codecov is not tracking our test coverage ... 
no coverage comment in the PR #70 and no recent tracking on the repo! 🤷‍♂ 
https://codecov.io/github/dwyl/hapi-error?branch=master
image

This is because our `.travis.yml` is not doing it's job ... 
https://github.com/dwyl/hapi-error/blob/c33c335dcd3a0fcab83c21d6679d756e53afb946/.travis.yml#L1-L6

the `after_success` command should be updated to:
```yml
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

Let's fix this ...

### PR DESCRIPTION
**Pull request by nelsonic**
In this PR I have refactored the code introduced in #70 to reduce the if/else nested statements without reduction in function of the code. This will bring us back up to 100% coverage. 
+ [x] Fixes #71

### CODE REVIEW

**Comment by nelsonic** [comment]
https://codecov.io/gh/dwyl/hapi-error/pulls indicates that sending reports to Codecov is working again:
image

**Comment by nelsonic** [comment]
@iteles this is a minor refactor to ensure 100% test coverage (_thanks to @Hydrock's work on #68_) 🎉 
updated the `.travis.yml` and `package.json` to ensure that Coverage reports are sent to Codecov. ✅ 
Please review and merge when possible so that I can publish a new version #66 ⏳

**Review by iteles — APPROVED** [review]
Thanks for this @nelsonic, ready to publish 👍

**Comment by nelsonic** [comment]
Thanks. 🌻

**Pull request merged**
