### PR TITLE
attempt to understand failing test 

### PR DESCRIPTION
**Pull request by nelsonic**
noted that tests failing in: https://github.com/dwyl/hapi-error/pull/55#issuecomment-485511030
attempting to _understand **why**_.

### CODE REVIEW

**Comment by nelsonic** [comment]
Travis-CI build appears to not be running ... 😞

**Comment by nelsonic** [comment]
Apparently the build has been failing for a `while` ... https://travis-ci.org/dwyl/hapi-error/requests
image

**Comment by nelsonic** [comment]
Tests are running/passing but not getting coverage of the branch added in #55 ... 😞 
image

**Comment by nelsonic** [comment]
@DavidHavl if you can help understand why the code on lines 113 - 116 are not being covered by the tests it would be _really_ helpful. thanks!

**Comment by DavidHavl** [comment]
@nelsonic It looks like the server.js line 45 needs to be `throw Boom.forbidden('Forbidden');` rather than using reply().

**Comment by DavidHavl** [comment]
#65

**Comment by DavidHavl** [comment]
Most of the tests seem to not be converted to HAPI >=17. I am almost done with the tests fix pull request.

**Comment by DavidHavl** [comment]
The tests are done (see pull request #65) but one test doesn't make sense. Please see the comment on #65

**Comment by nelsonic** [comment]
Fixed by #68 ✅ 
Closing.

**Pull request closed without merging**
