### PR TITLE
Benji's test

### PR DESCRIPTION
**Pull request by nelsonic**
@benjaminlees as discussed on Gitter, here's an example of an invalid route parameter being intercepted by the `onPreResponse` 
Please let me know if this answers your question. 👍 
See: #9

### CODE REVIEW

**Comment by benjaminlees** [comment]
@nelsonic reply is being fired before it even gets to this code in 
[conection.js](https://github.com/hapijs/hapi/blob/master/lib/connection.js)

**Comment by benjaminlees** [comment]
see 

```
internals.badRequest = function (request, reply) {

    return reply(Boom.badRequest());
};
```

**Comment by nelsonic** [comment]
@benjaminlees yes, the [`internals.badRequest`](https://github.com/hapijs/hapi/blob/22825a1175f0951ea90a5de79893de774df933bd/lib/connection.js#L418) does get invoked but the `Boom` is intercepted by `hapi-error` (or what ever `onPreResponse` you set up. e.g: http://hapi-error.herokuapp.com/register/22%3A%5B%22black%22%5D%7D%22%3E%3C%7%203cript%3Ealert%281%29%3C%2fscript%3E 
_or am I missing something...?_

**Comment by benjaminlees** [comment]
@nelsonic thanks for all your help. The issue was caused by our webpack dev server, which was rejecting the request before it made it to the server. We ran everything in build and now the onPreResponse event is being fired as expected.
Cheers.

**Comment by nelsonic** [comment]
Ah... _thanks_ `WebPack`... 😉

**Comment by nelsonic** [comment]
@benjaminlees please merge PR if you're happy. 
(_its just adding additional tests and docs..._) 👍

**Comment by ghost** [comment]
PR looks good. merging. 👍

**Pull request merged**
