### PR TITLE
Pass Hoek error object to Handlebars template for display on error page

### PR DESCRIPTION
**Pull request by naazy**
This Pull Request allows us to pass full objects into the `Hoek.assert` makes the properties of the error object available in the Handlebars (_or your choice of other view/template engine_) error page. see:   #19

### CODE REVIEW

**Comment by naazy** [comment]
@nelsonic - I can't figure out why the tests are failing. They are all passing individually but one of the tests is exiting without ending:

screen shot 2016-08-26 at 10 30 42

I have tried to put `server.stop(function(){ })` in t.end also but to no avail. Any idea why this might be happening? 😕

**Comment by nelsonic** [comment]
Ah... it's because the `500` error is "fatal"... 
We may need to have a _separate_ test for this feature...

**Comment by naazy** [comment]
@nelsonic a separate test for the redirect feature or handlebar props?

**Comment by nelsonic** [comment]
Hi @naazy testing Handlebar props _might_ need a separate `test/error_object_server_example.js`
Try following the example test for redirect feature where I _had_ to load a separate _server_:
- redirect test included in [`test/index.test.js`](https://github.com/dwyl/hapi-error/blob/8afdf95503996e0ebc3348a32dc70e183ab34016/test/index.test.js#L8)
- separate server: https://github.com/dwyl/hapi-error/blob/master/test/redirect_server_example.js

> shout if you get stuck! 👍

**Comment by naazy** [comment]
Thanks @nelsonic . That seemed to work and tests are now passing 🎉

**Comment by nelsonic** [comment]
@naazy nice work!
however the build on Travis https://travis-ci.org/dwyl/hapi-error/builds/155891891 (for this last commit) appears to be hanging. 
We might need a `process.exit()` at the end of the `test/index.test.js` file 
(_inside the `test.onFinish`_) to _ensure_ that it ends...?

**Comment by naazy** [comment]
@nelsonic Thanks! I have tried both stopping the redirect server and also adding process.exit but the tests still seem to be hanging... Any ideas?

**Comment by nelsonic** [comment]
@naazy updated the tests. 👍 
@iteles please review/comment/merge. thanks! 🎉

**Comment by iteles** [comment]
Nice work you two 🎉 

Hope this helps @naazy 👍

**Comment by nelsonic** [comment]
Nice work @naazy!! ✨ 
new version on NPM: `1.1.3` ✅

**Pull request merged**
