### PR TITLE
Add ability to use function for redirect parameter

### PR DESCRIPTION
**Pull request by DavidHavl**

### CODE REVIEW

**Comment by nelsonic** [comment]
@DavidHavl this would still be good functionality to have.
if you have time to update to Hapi v17 please do. 
thanks!

**Comment by DavidHavl** [comment]
@nelsonic Cool, will do.

**Comment by DavidHavl** [comment]
Sorry it took ages. I was super busy with work. I have now merged the code with upstream code and it should be ok now.

**Review by nelsonic — APPROVED** [review]
@DavidHavl using a `function` for redirect Docs, Tests & Code looks good. thanks! 🎉

**Comment by nelsonic** [comment]
Sadly when I attempt to run the tests on my `localhost` they fail:
image

**Comment by nelsonic** [comment]
I think the the _reason_ the tests fail on my localhost is because the PR did not merge successfully ... 😞 
see: https://github.com/dwyl/hapi-error/commits/master

**Pull request merged**
